# --- LOAN_STATUS_PREDICTION ---
# config/01_feature_engineering.yaml

# NOMBRE EXPERIMENTO
experiment_name: 'EXP_01'

# VARIABLE OBJETIVO
target_variable: 'loan_paid_back'

# SEMILLA
seed: 42

#VALIDACIÓN
data_split:
  test_size: 0.2
  stratify: true